import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";

const client = new Anthropic();

export async function POST(req: NextRequest) {
  const { text } = await req.json();
  if (!text || typeof text !== "string" || text.trim().length < 20) {
    return NextResponse.json({ error: "Please enter at least 20 characters of text." }, { status: 400 });
  }

  const systemPrompt = `You are an expert AI content detector. Your job is to analyze text and determine whether it was written by a human or generated by an AI model such as ChatGPT, GPT-4, GPT-5, Gemini, Claude, or similar large language models.

Analyze the text carefully for these signals:
- Repetitive sentence structures and overly uniform rhythm
- Lack of personality, anecdotes, or genuine emotion
- Unnaturally balanced perspectives without a personal stance
- Generic, hedging language ("it is important to note", "it is worth mentioning")
- Suspiciously perfect grammar and punctuation throughout
- Absence of typos, contractions, or informal language when expected
- Overly formal tone for the context
- Hollow transitions and generic conclusions
- Factual accuracy without contextual depth or personal experience

Return your analysis as a JSON object with EXACTLY this structure (no markdown, no extra text):
{
  "score": <integer 0-100, where 0 = definitely human, 100 = definitely AI>,
  "verdict": "<one of: 'Human Written', 'Likely Human', 'Mixed or Uncertain', 'Likely AI', 'AI Generated'>",
  "confidence": "<one of: 'Low', 'Medium', 'High'>",
  "signals": [
    { "label": "<signal name>", "detail": "<brief explanation>", "type": "<'ai' or 'human'>" }
  ],
  "summary": "<2-3 sentence plain-English explanation of your verdict>"
}

The signals array should have 3-5 entries. Be honest and nuanced — mixed content does exist.`;

  try {
    const message = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 1024,
      system: systemPrompt,
      messages: [{ role: "user", content: `Analyze this text:\n\n${text}` }],
    });

    const raw = message.content[0].type === "text" ? message.content[0].text : "";
    const cleaned = raw.replace(/```json|```/g, "").trim();
    const result = JSON.parse(cleaned);

    return NextResponse.json({ result });
  } catch (err) {
    console.error("AI detector error:", err);
    return NextResponse.json({ error: "Analysis failed. Please try again." }, { status: 500 });
  }
}
