import type { Metadata } from "next";
import QrCodeGeneratorClient from "./QrCodeGeneratorClient";

export const metadata: Metadata = {
  title: "QR Code Generator Free Online – Create QR Codes Instantly | SwiftoolAI",
  description:
    "Create QR codes for URLs, text, Wi-Fi, email, phone numbers, and more with SwiftoolAI's free QR Code Generator. Download as PNG instantly. No sign-up needed. Perfect for businesses, events, marketing, and personal use.",
  keywords: [
    "QR code generator free online",
    "create QR code for URL",
    "free QR code maker",
    "QR code generator no sign up",
    "custom QR code generator",
    "QR code for website link",
    "QR code for Wi-Fi",
    "QR code for business card",
    "download QR code PNG",
    "generate QR code instantly",
    "QR code marketing tool",
    "best free QR code generator",
    "QR code for events",
    "online QR code creator",
  ],
  openGraph: {
    title: "Free QR Code Generator — Create QR Codes Instantly | SwiftoolAI",
    description:
      "Create QR codes for URLs, text, Wi-Fi, email and more. Download as PNG instantly. Free, no sign-up.",
    url: "https://www.swiftoolai.com/tools/qr-code-generator",
    siteName: "SwiftoolAI",
    type: "website",
  },
  alternates: { canonical: "https://www.swiftoolai.com/tools/qr-code-generator" },
};

const SEOPARAGRAPH = `QR codes have become an essential tool for bridging the physical and digital worlds — from restaurant menus and event tickets to product packaging and marketing campaigns. SwiftoolAI's **QR Code Generator** makes creating high-quality QR codes fast, free, and effortless. Simply enter your URL, text, Wi-Fi credentials, email address, or phone number, and our tool generates a clean, scannable QR code ready to download as a PNG in seconds. Whether you're a business owner, marketer, event organizer, or individual needing a quick QR code solution, our free online generator delivers professional results with no restrictions and no registration required.`;

const FAQS = [
  {
    question: "What is SwiftoolAI's QR Code Generator?",
    answer:
      "It is a free online tool that creates scannable QR codes for URLs, text, Wi-Fi credentials, email addresses, phone numbers, and more — downloadable as PNG instantly.",
  },
  {
    question: "How do I create a QR code?",
    answer:
      "Select the content type (URL, text, Wi-Fi, etc.), enter your information, and click Generate. Your QR code appears instantly and can be downloaded as a PNG image.",
  },
  {
    question: "Is the QR Code Generator free?",
    answer:
      "Yes — completely free with no subscriptions, credits, or sign-up requirements.",
  },
  {
    question: "What types of QR codes can I create?",
    answer:
      "URL/website links, plain text, Wi-Fi network credentials, email addresses, phone numbers, and SMS messages.",
  },
  {
    question: "What format can I download the QR code in?",
    answer:
      "QR codes can be downloaded as PNG images, ready to use in print, digital, or social media materials.",
  },
  {
    question: "Do the generated QR codes expire?",
    answer:
      "No. QR codes generated by our tool contain static information and do not expire. They will work as long as the destination (e.g., a URL) remains active.",
  },
  {
    question: "Can I use QR codes for business and marketing?",
    answer:
      "Absolutely. QR codes are widely used on business cards, product packaging, menus, event tickets, posters, and digital marketing materials to link customers directly to websites, social media, or contact information.",
  },
  {
    question: "Do I need to sign up?",
    answer:
      "No account or sign-up needed. Create and download QR codes immediately.",
  },
];

const _s = {
  wrap: { maxWidth: 860, margin: "0 auto", padding: "2rem 1.25rem 4rem" } as React.CSSProperties,
  section: { background: "#fff", border: "1px solid rgba(0,0,0,0.08)", borderRadius: 16, padding: "1.75rem", marginBottom: "1.5rem", boxShadow: "0 2px 12px rgba(0,0,0,0.04)" } as React.CSSProperties,
  h2: { fontFamily: "'Syne', sans-serif", fontWeight: 700, fontSize: "1.3rem", color: "#111827", letterSpacing: "-0.02em", marginBottom: "1rem" } as React.CSSProperties,
  p: { color: "#6b7280", fontSize: 14, lineHeight: 1.75, marginBottom: "1rem" } as React.CSSProperties,
  tag: { display: "inline-block", fontSize: 11, fontWeight: 700, letterSpacing: "0.07em", textTransform: "uppercase" as const, color: "#2563eb", background: "#eff6ff", border: "1px solid #bfdbfe", borderRadius: 100, padding: "3px 10px", marginBottom: "0.75rem" },
  faqItem: (last: boolean) => ({ borderBottom: last ? "none" : "1px solid rgba(0,0,0,0.06)", paddingBottom: 16, marginBottom: 16 } as React.CSSProperties),
  faqQ: { fontWeight: 700, fontSize: 14, color: "#111827", marginBottom: 6 } as React.CSSProperties,
  link: { color: "#2563eb", fontSize: 13, textDecoration: "none" }  as React.CSSProperties,
};

export default function QrCodeGeneratorPage() {
  return (
    <>
      <QrCodeGeneratorClient />
      <div style={{..._s.wrap}}>

        <section style={{..._s.section}}>
          <div style={{..._s.tag}}>About</div>
          <h2 style={{..._s.h2}}>About Our Free QR Code Generator</h2>
          <p style={{..._s.p}}>{SEOPARAGRAPH}</p>
        </section>

        <section style={{..._s.section}}>
          <div style={{..._s.tag}}>FAQ</div>
          <h2 style={{..._s.h2}}>Frequently Asked Questions</h2>
          <div>
            {FAQS.map((faq, i) => (
              <div key={i} style={{..._s.faqItem(i === FAQS.length - 1)}}>
                <div style={{..._s.faqQ}}>{faq.question}</div>
                <p style={{..._s.p, marginBottom: 0}}>{faq.answer}</p>
              </div>
            ))}
          </div>
        </section>

        <section style={{..._s.section}}>
          <div style={{..._s.tag}}>More Tools</div>
          <h2 style={{..._s.h2}}>Explore More Free Tools</h2>
          <div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"6px 16px"}}>
            <a href="https://www.swiftoolai.com/tools/password-generator" style={{..._s.link}}>Password Generator</a>
            <a href="https://www.swiftoolai.com/tools/color-picker" style={{..._s.link}}>Color Picker</a>
            <a href="https://www.swiftoolai.com/tools/png-to-pdf" style={{..._s.link}}>PNG to PDF Converter</a>
            <a href="https://www.swiftoolai.com/tools/svg-to-png" style={{..._s.link}}>SVG to PNG Converter</a>
            <a href="https://www.swiftoolai.com/tools/image-compressor" style={{..._s.link}}>Image Compressor</a>
            <a href="https://www.swiftoolai.com/tools/word-counter" style={{..._s.link}}>Word Counter</a>
          </div>
        </section>

      </div>
    </>
  );
}
