"use client";
import { useState, useRef } from "react";
import { useSession, signIn } from "next-auth/react";
import Link from "next/link";

type Signal = { label: string; detail: string; type: "ai" | "human" };

type DetectionResult = {
  score: number;
  verdict: string;
  confidence: string;
  signals: Signal[];
  summary: string;
};

function getScoreColor(score: number) {
  if (score <= 25) return { bar: "#16a34a", bg: "#f0fdf4", border: "#bbf7d0", text: "#15803d" };
  if (score <= 50) return { bar: "#ca8a04", bg: "#fefce8", border: "#fde68a", text: "#a16207" };
  if (score <= 75) return { bar: "#ea580c", bg: "#fff7ed", border: "#fed7aa", text: "#c2410c" };
  return { bar: "#dc2626", bg: "#fef2f2", border: "#fecaca", text: "#b91c1c" };
}

function VerdictBadge({ verdict, score }: { verdict: string; score: number }) {
  const colors = getScoreColor(score);
  const emoji =
    score <= 25 ? "✅" : score <= 50 ? "🟡" : score <= 75 ? "🟠" : "🤖";
  return (
    <span
      style={{
        display: "inline-flex",
        alignItems: "center",
        gap: 6,
        fontSize: 13,
        fontWeight: 700,
        background: colors.bg,
        color: colors.text,
        border: `1px solid ${colors.border}`,
        borderRadius: 100,
        padding: "4px 12px",
      }}
    >
      {emoji} {verdict}
    </span>
  );
}

export default function AIDetectorClient() {
  const { data: session, status } = useSession();
  const [text, setText] = useState("");
  const [result, setResult] = useState<DetectionResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const abortRef = useRef<AbortController | null>(null);

  const MIN_CHARS = 50;
  const MAX_CHARS = 3000;
  const wordCount = text.trim() ? text.trim().split(/\s+/).length : 0;

  // Loading skeleton
  if (status === "loading") {
    return (
      <div style={{ maxWidth: 820, margin: "0 auto", padding: "3rem 1.25rem" }}>
        {[300, 200, 400].map((h, i) => (
          <div key={i} style={{ height: h, background: "#f3f4f6", borderRadius: 12, marginBottom: "1rem", animation: "pulse 1.5s ease-in-out infinite" }} />
        ))}
        <style>{`@keyframes pulse{0%,100%{opacity:1}50%{opacity:.5}}`}</style>
      </div>
    );
  }

  // Auth gate
  if (status === "unauthenticated") {
    return (
      <div style={{ maxWidth: 820, margin: "0 auto", padding: "3rem 1.25rem" }}>
        <h1 style={{ fontFamily: "'Syne', sans-serif", fontWeight: 800, fontSize: "clamp(1.8rem,4vw,2.5rem)", letterSpacing: "-0.03em", marginBottom: "0.6rem", color: "#111827" }}>
          AI Detector — Trusted AI Checker
        </h1>
        <p style={{ color: "#6b7280", fontSize: 16, lineHeight: 1.6, marginBottom: "2rem" }}>
          Detect whether text was written by a human or generated by ChatGPT, GPT-5, Gemini, or other AI models.
        </p>
        <div style={{ position: "relative", borderRadius: 12, overflow: "hidden", marginBottom: "1.5rem" }}>
          <div style={{ filter: "blur(3px)", pointerEvents: "none", userSelect: "none", opacity: 0.5, background: "#fff", border: "1px solid rgba(0,0,0,0.08)", borderRadius: 12, padding: "2rem", minHeight: 280 }}>
            <div style={{ height: 12, background: "#f3f4f6", borderRadius: 4, marginBottom: 10, width: "90%" }} />
            <div style={{ height: 12, background: "#f3f4f6", borderRadius: 4, marginBottom: 10, width: "75%" }} />
            <div style={{ height: 12, background: "#f3f4f6", borderRadius: 4, marginBottom: 10, width: "85%" }} />
          </div>
          <div style={{ position: "absolute", inset: 0, display: "flex", alignItems: "center", justifyContent: "center", background: "rgba(249,250,251,0.85)", backdropFilter: "blur(2px)" }}>
            <div style={{ background: "#fff", border: "1px solid rgba(0,0,0,0.1)", borderRadius: 16, padding: "2rem 2.5rem", textAlign: "center", maxWidth: 380, boxShadow: "0 8px 40px rgba(0,0,0,0.1)" }}>
              <div style={{ fontSize: 32, marginBottom: "0.75rem" }}>🤖</div>
              <h2 style={{ fontFamily: "'Syne',sans-serif", fontWeight: 700, fontSize: "1.2rem", color: "#111827", marginBottom: "0.5rem" }}>Sign in to use AI Detector</h2>
              <p style={{ fontSize: 14, color: "#6b7280", lineHeight: 1.6, marginBottom: "1.5rem" }}>Free access to our AI content detector and 25+ AI tools. Takes 10 seconds.</p>
              <button
                onClick={() => signIn("google", { callbackUrl: window.location.href })}
                style={{ width: "100%", padding: "12px 20px", background: "#fff", border: "1.5px solid #e5e7eb", borderRadius: 9, display: "flex", alignItems: "center", justifyContent: "center", gap: 10, fontSize: 14, fontWeight: 600, color: "#111827", cursor: "pointer", boxShadow: "0 1px 4px rgba(0,0,0,0.06)" }}
              >
                Continue with Google — free
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  async function handleAnalyze() {
    if (text.trim().length < MIN_CHARS || loading) return;
    setLoading(true);
    setError("");
    setResult(null);
    abortRef.current = new AbortController();

    try {
      const res = await fetch("/api/ai-detector", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text }),
        signal: abortRef.current.signal,
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Analysis failed");
      setResult(data.result);
    } catch (err) {
      if ((err as Error).name === "AbortError") return;
      setError(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }

  const colors = result ? getScoreColor(result.score) : null;

  return (
    <div style={{ maxWidth: 820, margin: "0 auto", padding: "3rem 1.25rem 5rem" }}>
      {/* Header */}
      <div style={{ marginBottom: "2rem" }}>
        <h1 style={{ fontFamily: "'Syne', sans-serif", fontWeight: 800, fontSize: "clamp(1.8rem,4vw,2.4rem)", letterSpacing: "-0.03em", marginBottom: "0.5rem", color: "#111827" }}>
          AI Detector
        </h1>
        <p style={{ color: "#6b7280", fontSize: 15, lineHeight: 1.6 }}>
          Paste any text to detect whether it was written by a human or generated by an AI model like ChatGPT, GPT-5, or Gemini.
        </p>
      </div>

      {/* Input card */}
      <div style={{ background: "#fff", border: "1px solid rgba(0,0,0,0.08)", borderRadius: 16, overflow: "hidden", marginBottom: "1rem", boxShadow: "0 2px 12px rgba(0,0,0,0.04)" }}>
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 16px", borderBottom: "1px solid rgba(0,0,0,0.06)", background: "#f9fafb" }}>
          <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.07em", textTransform: "uppercase", color: "#9ca3af" }}>Paste text to analyze</span>
          <span style={{ fontSize: 11, color: text.length > MAX_CHARS * 0.9 ? "#ef4444" : "#9ca3af" }}>
            {wordCount} words · {text.length}/{MAX_CHARS}
          </span>
        </div>
        <textarea
          value={text}
          onChange={e => setText(e.target.value.slice(0, MAX_CHARS))}
          placeholder="Paste any text here — an article, essay, email, blog post, or social media caption — and our AI detector will analyze whether it was written by a human or generated by ChatGPT, GPT-5, Gemini, or another AI model..."
          style={{ width: "100%", minHeight: 220, border: "none", outline: "none", resize: "none", padding: "16px", fontSize: 15, color: "#111827", lineHeight: 1.7, background: "transparent", boxSizing: "border-box", fontFamily: "inherit" }}
        />
      </div>

      {/* Char hint */}
      {text.length > 0 && text.length < MIN_CHARS && (
        <p style={{ fontSize: 12, color: "#9ca3af", marginBottom: "0.75rem" }}>
          Add {MIN_CHARS - text.length} more characters to enable analysis
        </p>
      )}

      {error && (
        <div style={{ background: "#fef2f2", border: "1px solid #fecaca", borderRadius: 9, padding: "10px 14px", fontSize: 13, color: "#dc2626", marginBottom: "1rem" }}>
          {error}
        </div>
      )}

      {/* Analyze button */}
      <button
        onClick={handleAnalyze}
        disabled={text.trim().length < MIN_CHARS || loading}
        style={{ width: "100%", padding: "14px", background: "#2563eb", color: "#fff", border: "none", borderRadius: 10, fontSize: 15, fontWeight: 700, cursor: text.trim().length >= MIN_CHARS && !loading ? "pointer" : "not-allowed", opacity: text.trim().length >= MIN_CHARS && !loading ? 1 : 0.45, marginBottom: "2rem", transition: "opacity 0.15s", boxShadow: "0 2px 8px rgba(37,99,235,0.25)", letterSpacing: "0.01em" }}
      >
        {loading ? "Analyzing text…" : "Analyze with AI Detector →"}
      </button>

      {/* Loading state */}
      {loading && (
        <div style={{ background: "#fff", border: "1px solid rgba(0,0,0,0.08)", borderRadius: 16, padding: "2.5rem", textAlign: "center", boxShadow: "0 2px 12px rgba(0,0,0,0.04)", marginBottom: "1.5rem" }}>
          <div style={{ width: 40, height: 40, border: "3px solid #bfdbfe", borderTopColor: "#2563eb", borderRadius: "50%", animation: "spin 0.7s linear infinite", margin: "0 auto 1rem" }} />
          <p style={{ fontSize: 14, color: "#6b7280" }}>Running AI detection analysis…</p>
          <style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style>
        </div>
      )}

      {/* Result card */}
      {result && colors && (
        <div style={{ animation: "fadeIn 0.35s ease" }}>
          {/* Score panel */}
          <div style={{ background: "#fff", border: `1.5px solid ${colors.border}`, borderRadius: 16, padding: "2rem", marginBottom: "1rem", boxShadow: "0 2px 12px rgba(0,0,0,0.04)" }}>
            <div style={{ display: "flex", alignItems: "flex-start", justifyContent: "space-between", flexWrap: "wrap", gap: 12, marginBottom: "1.5rem" }}>
              <div>
                <div style={{ fontSize: 12, fontWeight: 700, letterSpacing: "0.07em", textTransform: "uppercase", color: "#9ca3af", marginBottom: 6 }}>Detection Result</div>
                <VerdictBadge verdict={result.verdict} score={result.score} />
                <div style={{ fontSize: 12, color: "#9ca3af", marginTop: 6 }}>Confidence: <strong style={{ color: "#374151" }}>{result.confidence}</strong></div>
              </div>
              {/* Score circle */}
              <div style={{ textAlign: "center" }}>
                <div style={{ width: 80, height: 80, borderRadius: "50%", background: colors.bg, border: `3px solid ${colors.bar}`, display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column" }}>
                  <span style={{ fontSize: 22, fontWeight: 800, color: colors.text, lineHeight: 1 }}>{result.score}</span>
                  <span style={{ fontSize: 9, fontWeight: 700, color: colors.text, letterSpacing: "0.05em", textTransform: "uppercase" }}>AI Score</span>
                </div>
              </div>
            </div>

            {/* Score bar */}
            <div style={{ marginBottom: "1.25rem" }}>
              <div style={{ display: "flex", justifyContent: "space-between", fontSize: 11, color: "#9ca3af", marginBottom: 6 }}>
                <span>Human Written</span><span>AI Generated</span>
              </div>
              <div style={{ height: 10, background: "#f3f4f6", borderRadius: 100, overflow: "hidden" }}>
                <div style={{ height: "100%", width: `${result.score}%`, background: colors.bar, borderRadius: 100, transition: "width 0.8s cubic-bezier(0.16,1,0.3,1)" }} />
              </div>
            </div>

            <p style={{ fontSize: 14, color: "#374151", lineHeight: 1.7, margin: 0 }}>{result.summary}</p>
          </div>

          {/* Signals */}
          <div style={{ background: "#fff", border: "1px solid rgba(0,0,0,0.08)", borderRadius: 16, padding: "1.5rem", marginBottom: "1rem", boxShadow: "0 2px 12px rgba(0,0,0,0.04)" }}>
            <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.07em", textTransform: "uppercase", color: "#9ca3af", marginBottom: "1rem" }}>Detection Signals</div>
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {result.signals.map((sig, i) => (
                <div key={i} style={{ display: "flex", alignItems: "flex-start", gap: 12, padding: "12px 14px", background: sig.type === "ai" ? "#fef2f2" : "#f0fdf4", borderRadius: 10, border: `1px solid ${sig.type === "ai" ? "#fecaca" : "#bbf7d0"}` }}>
                  <span style={{ fontSize: 14, flexShrink: 0, marginTop: 1 }}>{sig.type === "ai" ? "🤖" : "✍️"}</span>
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 700, color: sig.type === "ai" ? "#b91c1c" : "#15803d", marginBottom: 2 }}>{sig.label}</div>
                    <div style={{ fontSize: 13, color: "#6b7280", lineHeight: 1.5 }}>{sig.detail}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Try again */}
          <button onClick={() => { setResult(null); setText(""); }} style={{ width: "100%", padding: "11px", background: "transparent", border: "1px solid rgba(0,0,0,0.1)", borderRadius: 10, fontSize: 14, fontWeight: 600, color: "#374151", cursor: "pointer", marginBottom: "1rem" }}>
            ← Analyze Another Text
          </button>
        </div>
      )}

      <style>{`@keyframes fadeIn{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}`}</style>
    </div>
  );
}
