import type { Metadata } from "next";
import AIDetectorClient from "./AIDetectorClient";

export const metadata: Metadata = {
  title: "AI Detector - Trusted AI Checker for ChatGPT, GPT5 & Gemini | SwiftoolAI",
  description:
    "An AI detector (also called an AI checker or AI content detector) analyzes text to evaluate how likely it was generated by AI. Detect whether text is AI-generated by ChatGPT, GPT-5, or Gemini — free.",
  alternates: { canonical: "https://www.swiftoolai.com/tools/ai-detector" },
  openGraph: {
    title: "AI Detector - Trusted AI Checker for ChatGPT, GPT5 & Gemini",
    description:
      "Free AI content detector. Paste any text and instantly check whether it was written by a human or generated by ChatGPT, GPT-5, Gemini, or another AI model.",
    url: "https://www.swiftoolai.com/tools/ai-detector",
    siteName: "SwiftoolAI",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "AI Detector - Trusted AI Checker for ChatGPT, GPT5 & Gemini",
    description:
      "Detect AI-generated text from ChatGPT, GPT-5, Gemini, and more. Free AI content detector — no sign-up needed.",
  },
  keywords: [
    "AI detector",
    "AI text detector",
    "AI content detector",
    "AI checker",
    "ChatGPT detector",
    "GPT5 detector",
    "Gemini detector",
    "detect AI writing",
    "AI generated text checker",
    "free AI detector",
  ],
};

const _s = {
  wrap: { maxWidth: 860, margin: "0 auto", padding: "0 1.25rem 5rem" } as React.CSSProperties,
  section: {
    background: "#fff",
    border: "1px solid rgba(0,0,0,0.08)",
    borderRadius: 16,
    padding: "1.75rem",
    marginBottom: "1.5rem",
    boxShadow: "0 2px 12px rgba(0,0,0,0.04)",
  } as React.CSSProperties,
  h2: {
    fontFamily: "'Syne', sans-serif",
    fontWeight: 700,
    fontSize: "1.3rem",
    color: "#111827",
    letterSpacing: "-0.02em",
    marginBottom: "1rem",
  } as React.CSSProperties,
  h3: {
    fontWeight: 700,
    fontSize: "0.9rem",
    color: "#111827",
    marginBottom: "0.4rem",
  } as React.CSSProperties,
  p: { color: "#6b7280", fontSize: 14, lineHeight: 1.8, marginBottom: "1rem" } as React.CSSProperties,
  tag: {
    display: "inline-block",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.07em",
    textTransform: "uppercase" as const,
    color: "#2563eb",
    background: "#eff6ff",
    border: "1px solid #bfdbfe",
    borderRadius: 100,
    padding: "3px 10px",
    marginBottom: "0.75rem",
  },
  faqItem: (last: boolean) =>
    ({
      borderBottom: last ? "none" : "1px solid rgba(0,0,0,0.06)",
      paddingBottom: 16,
      marginBottom: 16,
    } as React.CSSProperties),
  faqQ: { fontWeight: 700, fontSize: 14, color: "#111827", marginBottom: 6 } as React.CSSProperties,
  link: { color: "#2563eb", fontSize: 13, textDecoration: "none" } as React.CSSProperties,
};

const FAQS = [
  {
    question: "What is an AI detector?",
    answer:
      "An AI detector (also called an AI checker or AI content detector) is a tool that analyzes text to evaluate how likely it was generated by an AI model such as ChatGPT, GPT-5, Gemini, or Claude. It looks for patterns in sentence structure, vocabulary, and writing style that are characteristic of AI-generated content versus human writing.",
  },
  {
    question: "Which AI models can this AI text detector identify?",
    answer:
      "Our AI text detector is trained to recognize writing patterns from ChatGPT (GPT-3.5, GPT-4, GPT-5), Gemini (formerly Bard), Claude, Llama, Mistral, and other large language models. As AI writing evolves, our AI checker is regularly updated to keep pace.",
  },
  {
    question: "How accurate is this AI content detector?",
    answer:
      "Our AI content detector is highly accurate for clearly AI-generated or clearly human-written text. Like all AI detectors, accuracy decreases for heavily edited AI text or text written in an unusually formal human style. We always display a confidence level alongside the verdict so you can judge how certain the result is.",
  },
  {
    question: "Is this AI checker free to use?",
    answer:
      "Yes — our AI checker is completely free. Create a free SwiftoolAI account (just a Google sign-in) to access the AI detector and all 25+ tools on the platform.",
  },
  {
    question: "Can the AI detector detect ChatGPT specifically?",
    answer:
      "Yes. ChatGPT text tends to have distinctive patterns: uniform sentence length, overly balanced arguments, absence of genuine personal opinion, and a tendency toward formal transitional phrases. Our AI detector flags these patterns with labelled detection signals so you can see exactly why a score was assigned.",
  },
  {
    question: "Can this tool detect AI-generated images?",
    answer:
      "This tool focuses on AI text detection. For image analysis, check our AI Face Rater tool which uses image-based AI analysis.",
  },
  {
    question: "Will the AI detector work on short texts?",
    answer:
      "We require a minimum of 50 characters for a reliable result. Shorter text doesn't give the AI detector enough signals to make a confident judgment. For best accuracy, paste at least 150 words.",
  },
  {
    question: "Is my text stored or shared?",
    answer:
      "No. Text you submit to our AI content detector is processed in real time and never stored on our servers. Your content stays private.",
  },
];

// JSON-LD schemas
const webPageSchema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "AI Detector - Trusted AI Checker for ChatGPT, GPT5 & Gemini",
  description:
    "An AI detector (also called an AI checker or AI content detector) analyzes text to evaluate how likely it was generated by AI. Detect whether text is AI-generated by ChatGPT, GPT-5, or Gemini.",
  url: "https://www.swiftoolai.com/tools/ai-detector",
  isPartOf: { "@type": "WebSite", name: "SwiftoolAI", url: "https://www.swiftoolai.com" },
};

const softwareSchema = {
  "@context": "https://schema.org",
  "@type": "SoftwareApplication",
  name: "AI Detector",
  description:
    "A free AI content detector that analyzes text to determine if it was written by a human or generated by ChatGPT, GPT-5, Gemini, or other AI models.",
  url: "https://www.swiftoolai.com/tools/ai-detector",
  applicationCategory: "UtilityApplication",
  operatingSystem: "Web",
  offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
  featureList: [
    "ChatGPT text detection",
    "GPT-5 detection",
    "Gemini AI detector",
    "AI content scoring",
    "Human vs AI writing analysis",
    "Detection signal breakdown",
  ],
};

const faqSchema = {
  "@context": "https://schema.org",
  "@type": "FAQPage",
  mainEntity: FAQS.map((faq) => ({
    "@type": "Question",
    name: faq.question,
    acceptedAnswer: { "@type": "Answer", text: faq.answer },
  })),
};

export default function AIDetectorPage() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(webPageSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(softwareSchema) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }}
      />

      {/* Interactive tool */}
      <AIDetectorClient />

      {/* SEO content below the fold */}
      <div style={_s.wrap}>
        {/* About section */}
        <section style={_s.section}>
          <div style={_s.tag}>About</div>
          <h2 style={_s.h2}>About Our Free AI Detector</h2>
          <p style={_s.p}>
            SwiftoolAI&apos;s <strong>AI detector</strong> is a trusted, free AI checker that analyzes any piece of text and evaluates how likely it was generated by an AI model. Whether you need to detect output from <strong>ChatGPT</strong>, <strong>GPT-5</strong>, or <strong>Gemini</strong>, our AI text detector produces a scored verdict with clearly labelled detection signals — so you always understand <em>why</em> a decision was made, not just what it was.
          </p>
          <p style={_s.p}>
            As an <strong>AI content detector</strong>, the tool scans for patterns that distinguish AI-generated writing from human writing: unnaturally consistent sentence rhythm, absence of personal voice, overly hedged language, and generic structural choices. Each analysis returns an AI score from 0 to 100, a confidence level, and a set of specific signals explaining the result.
          </p>
          <p style={_s.p}>
            Our AI checker is built for teachers checking student submissions, editors verifying freelance content, hiring managers reviewing cover letters, and anyone who wants to know whether the text in front of them was written by a human or produced by an AI model. It is completely free to use with a SwiftoolAI account.
          </p>
        </section>

        {/* How it works */}
        <section style={_s.section}>
          <div style={_s.tag}>How It Works</div>
          <h2 style={_s.h2}>How Our AI Text Detector Works</h2>
          <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))", gap: "1rem" }}>
            {[
              {
                icon: "📋",
                title: "1. Paste your text",
                body: "Copy and paste any text you want to check — a blog post, essay, email, or social caption. Our AI detector works best with 150+ words.",
              },
              {
                icon: "🔍",
                title: "2. AI analysis runs",
                body: "Our AI content detector scans your text for the structural, stylistic, and linguistic patterns that distinguish AI-generated content from human writing.",
              },
              {
                icon: "📊",
                title: "3. Get your AI score",
                body: "Receive an AI score from 0–100, a plain-English verdict (Human Written, Likely AI, etc.), and specific detection signals with explanations.",
              },
            ].map((step) => (
              <div key={step.title} style={{ padding: "1.25rem", background: "#f9fafb", borderRadius: 12, border: "1px solid rgba(0,0,0,0.06)" }}>
                <div style={{ fontSize: 24, marginBottom: 8 }}>{step.icon}</div>
                <h3 style={_s.h3}>{step.title}</h3>
                <p style={{ ..._s.p, marginBottom: 0 }}>{step.body}</p>
              </div>
            ))}
          </div>
        </section>

        {/* What we detect */}
        <section style={_s.section}>
          <div style={_s.tag}>Detection Signals</div>
          <h2 style={_s.h2}>What Our AI Checker Looks For</h2>
          <p style={_s.p}>
            Our AI content detector identifies the following patterns commonly found in AI-generated text:
          </p>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px 1.5rem" }}>
            {[
              "Uniform sentence rhythm and length",
              "Absence of personal voice or opinion",
              "Overuse of hedging phrases",
              "Generic transitional language",
              "Suspiciously perfect grammar throughout",
              "No typos, contractions, or colloquialisms",
              "Hollow conclusions or summaries",
              "Overly balanced, uncommitted arguments",
              "Repeated structural templates",
              "Lack of anecdote or lived experience",
            ].map((item) => (
              <div key={item} style={{ display: "flex", alignItems: "flex-start", gap: 8, fontSize: 13, color: "#374151", padding: "5px 0" }}>
                <span style={{ color: "#2563eb", flexShrink: 0, marginTop: 1 }}>✓</span>
                {item}
              </div>
            ))}
          </div>
        </section>

        {/* FAQ */}
        <section style={_s.section}>
          <div style={_s.tag}>FAQ</div>
          <h2 style={_s.h2}>Frequently Asked Questions</h2>
          <div>
            {FAQS.map((faq, i) => (
              <div key={i} style={_s.faqItem(i === FAQS.length - 1)}>
                <div style={_s.faqQ}>{faq.question}</div>
                <p style={{ ..._s.p, marginBottom: 0 }}>{faq.answer}</p>
              </div>
            ))}
          </div>
        </section>

        {/* More tools */}
        <section style={_s.section}>
          <div style={_s.tag}>More Tools</div>
          <h2 style={_s.h2}>More Free AI Tools</h2>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "6px 16px" }}>
            {[
              ["Grammar Checker", "/tools/grammar-checker"],
              ["Paraphrasing Tool", "/tools/paraphrasing-tool"],
              ["AI Summarizer", "/tools/ai-summarizer"],
              ["Text Rewriter", "/tools/rewriter"],
              ["AI Email Writer", "/tools/ai-email-writer"],
              ["Cover Letter Generator", "/tools/cover-letter-generator"],
            ].map(([label, href]) => (
              <a
                key={label}
                href={`https://www.swiftoolai.com${href}`}
                style={_s.link}
              >
                {label}
              </a>
            ))}
          </div>
        </section>
      </div>
    </>
  );
}
